import {
  codeBlock,
  heading,
  inlineCode,
  link,
  list,
  paragraph,
  type DocPage,
} from './types';

const guideSection = 'Guide';
const guideSectionOrder = 1;

export const guidePages: DocPage[] = [
  {
    path: '/guide/getting-started/',
    title: '快速开始',
    description: '安装 TSone，创建第一个类组件应用，并使用 Bun 启动示例。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 1,
    body: [
      heading(1, '快速开始'),
      paragraph('本指南将帮助您快速上手 TSone 框架。'),
      heading(2, '安装'),
      paragraph('首先，您需要安装 TSone 包。项目默认使用 Bun：'),
      codeBlock('bash', 'bun add @geektech/tsone'),
      heading(2, '创建第一个应用'),
      heading(3, '1. 创建一个简单的组件'),
      codeBlock(
        'ts',
        [
          "import { Component, VNode, createApp } from '@geektech/tsone';",
          '',
          'interface AppState {',
          '  count: number;',
          '}',
          '',
          'class App extends Component<object, AppState> {',
          '  protected initState(): AppState {',
          '    return { count: 0 };',
          '  }',
          '',
          '  protected initStyles(): void {',
          "    this.styleManager.addStyle('.app', {",
          "      selector: '.app',",
          '      properties: {',
          "        textAlign: 'center',",
          "        padding: '20px',",
          '      },',
          '    });',
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          "      props: { className: 'app' },",
          '      children: [',
          "        { tag: 'h1', children: ['计数: {{count}}'] },",
          '        {',
          "          tag: 'button',",
          "          props: { className: 'btn' },",
          '          listeners: {',
          '            click: () => this.state.count++,',
          '          },',
          "          children: ['增加计数'],",
          '        },',
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(3, '2. 创建应用实例并挂载'),
      codeBlock(
        'ts',
        [
          'const app = createApp({',
          '  root: App,',
          "  rootElement: '#app',",
          '  state: {',
          "    appName: 'TSone 示例',",
          '  },',
          '});',
          '',
          'app.mount();',
        ].join('\n')
      ),
      heading(3, '3. HTML 结构'),
      codeBlock(
        'html',
        [
          '<!DOCTYPE html>',
          '<html lang="zh-CN">',
          '  <head>',
          '    <meta charset="UTF-8" />',
          '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
          '    <title>TSone 示例</title>',
          '  </head>',
          '  <body>',
          '    <div id="app"></div>',
          '    <script type="module" src="./index.ts"></script>',
          '  </body>',
          '</html>',
        ].join('\n')
      ),
      heading(2, '运行应用'),
      codeBlock('bash', 'bun run dev'),
      paragraph(
        '现在，您应该能看到一个简单的计数器应用，点击按钮可以增加计数。'
      ),
      heading(2, '下一步'),
      list([
        ['了解 ', link('核心概念', '/guide/core-concepts/')],
        ['学习 ', link('组件系统', '/guide/component-system/')],
        ['探索 ', link('响应式系统', '/guide/reactive-system/')],
        ['掌握 ', link('路由系统', '/guide/router-system/')],
        ['了解 ', link('样式管理', '/guide/style-management/')],
      ]),
    ],
  },
  {
    path: '/guide/core-concepts/',
    title: '核心概念',
    description: '理解应用实例、类组件、响应式系统、路由和样式管理之间的关系。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 2,
    body: [
      heading(1, '核心概念'),
      paragraph(
        '本文档介绍 TSone 框架的核心概念，帮助您更好地理解框架的设计理念和工作原理。'
      ),
      heading(2, '1. 应用实例'),
      paragraph(
        '应用实例是 TSone 应用的入口点，通过 ',
        inlineCode('createApp'),
        ' 创建。'
      ),
      codeBlock(
        'ts',
        [
          "import { createApp } from '@geektech/tsone';",
          '',
          'const app = createApp({',
          "  rootElement: '#app',",
          '  state: {',
          "    appName: 'My App',",
          '  },',
          '});',
          '',
          'app.mount();',
        ].join('\n')
      ),
      heading(2, '2. 组件'),
      paragraph(
        '所有组件都继承 ',
        inlineCode('Component<Props, State>'),
        '，通过 ',
        inlineCode('protected render(): VNode'),
        ' 描述 UI。'
      ),
      heading(3, '组件生命周期'),
      list([
        [inlineCode('beforeMount()'), ': 组件挂载前调用'],
        [inlineCode('onMounted()'), ': 组件挂载后调用'],
        [inlineCode('beforeUpdate()'), ': 组件更新前调用'],
        [inlineCode('onUpdated()'), ': 组件更新后调用'],
        [inlineCode('beforeUnmount()'), ': 组件卸载前调用'],
        [inlineCode('onUnmounted()'), ': 组件卸载后调用'],
      ]),
      heading(3, '组件渲染'),
      paragraph(
        '组件通过 ',
        inlineCode('render()'),
        ' 返回虚拟节点，渲染器会根据 VNode 类型选择文本、元素、组件或插槽策略。'
      ),
      heading(2, '3. 响应式系统'),
      paragraph(
        'TSone 的响应式系统基于 Proxy 实现，常用 API 包括 ',
        inlineCode('reactive'),
        '、',
        inlineCode('effect'),
        '、',
        inlineCode('computed'),
        '、',
        inlineCode('readonly'),
        '、',
        inlineCode('ref'),
        ' 和 ',
        inlineCode('stop'),
        '。'
      ),
      heading(3, '核心 API'),
      list([
        [inlineCode('reactive(target)'), ': 创建响应式对象'],
        [inlineCode('effect(fn)'), ': 创建副作用函数'],
        [inlineCode('computed(fn)'), ': 创建计算属性'],
        [inlineCode('readonly(target)'), ': 创建只读响应式对象'],
        [inlineCode('ref(value)'), ': 创建包装单值的响应式引用'],
      ]),
      heading(2, '4. 虚拟 DOM'),
      paragraph('虚拟 DOM 是对真实 DOM 的轻量级抽象。'),
      heading(3, '虚拟 DOM 结构'),
      codeBlock(
        'ts',
        [
          'const vnode = {',
          "  tag: 'div',",
          "  props: { className: 'container' },",
          '  listeners: {',
          "    click: () => console.log('clicked'),",
          '  },',
          '  children: [',
          "    'Hello World',",
          "    { tag: 'button', children: ['Click Me'] },",
          '  ],',
          '};',
          '',
          'const componentVnode = {',
          '  component: MyComponent,',
          "  props: { title: 'My Component' },",
          '};',
        ].join('\n')
      ),
      heading(2, '5. 路由系统'),
      paragraph(
        '通过 ',
        inlineCode('createRouter'),
        ' 创建路由实例，并使用 ',
        inlineCode('RouterView'),
        ' 与 ',
        inlineCode('RouterLink'),
        ' 参与渲染和导航。'
      ),
      heading(3, '路由配置'),
      codeBlock(
        'ts',
        [
          "import { createRouter } from '@geektech/tsone/router';",
          '',
          'const router = createRouter({',
          '  routes: [',
          "    { path: '/', component: HomeComponent, meta: { title: '首页' } },",
          "    { path: '/about', component: AboutComponent, meta: { title: '关于我们' } },",
          '  ],',
          "  mode: 'history',",
          "  base: '/',",
          '});',
        ].join('\n')
      ),
      heading(2, '6. 样式管理'),
      paragraph(
        'TSone 提供内置 ',
        inlineCode('StyleManager'),
        '，每个组件实例都可以通过 ',
        inlineCode('this.styleManager'),
        ' 管理样式。'
      ),
      heading(3, '样式定义'),
      codeBlock(
        'ts',
        [
          'protected initStyles() {',
          "  this.styleManager.addStyle('.container', {",
          "    selector: '.container',",
          '    properties: {',
          "      width: '100%',",
          "      maxWidth: '1200px',",
          "      margin: '0 auto',",
          '    },',
          '  });',
          '}',
        ].join('\n')
      ),
      heading(2, '7. 插件系统'),
      paragraph('插件通过 app.use() 安装，可向应用上下文和组件扩展能力。'),
      heading(3, '插件示例'),
      codeBlock(
        'ts',
        [
          'const myPlugin = {',
          '  install(app: { myMethod?: () => void }) {',
          '    app.myMethod = () => {',
          "      console.log('My plugin method');",
          '    };',
          '  },',
          '};',
          '',
          'app.use(myPlugin);',
        ].join('\n')
      ),
      heading(2, '8. 事件系统'),
      paragraph('组件可以通过 emit/on 进行事件通知。'),
      heading(3, '事件示例'),
      codeBlock(
        'ts',
        [
          "this.emit('custom-event', 'event data');",
          '',
          "component.on('custom-event', (data) => {",
          "  console.log('Event received:', data);",
          '});',
        ].join('\n')
      ),
      heading(2, '总结'),
      paragraph(
        '以上概念共同组成 TSone 的应用模型；继续阅读 ',
        link('组件系统', '/guide/component-system/'),
        '、',
        link('响应式系统', '/guide/reactive-system/'),
        ' 与 ',
        link('路由系统', '/guide/router-system/'),
        ' 可以看到更具体的代码模式。'
      ),
    ],
  },
  {
    path: '/guide/component-system/',
    title: '组件系统',
    description:
      '学习基于 Component<Props, State> 的类组件、生命周期、事件和插槽。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 3,
    body: [
      heading(1, '组件系统'),
      paragraph('TSone 的组件系统允许您将 UI 拆分为独立、可复用的类组件。'),
      heading(2, '组件定义'),
      paragraph(
        '组件通过继承 ',
        inlineCode('Component<Props, State>'),
        ' 定义，并实现 ',
        inlineCode('initState()'),
        '、',
        inlineCode('initStyles()'),
        ' 和 ',
        inlineCode('protected render(): VNode'),
        '。'
      ),
      heading(3, '基本组件结构'),
      codeBlock(
        'ts',
        [
          "import { Component, VNode } from '@geektech/tsone';",
          '',
          'interface MessageState {',
          '  message: string;',
          '}',
          '',
          'class MyComponent extends Component<object, MessageState> {',
          '  protected initState(): MessageState {',
          "    return { message: 'Hello, TSone!' };",
          '  }',
          '',
          '  protected initStyles(): void {',
          "    this.styleManager.addStyle('.my-component', {",
          "      selector: '.my-component',",
          '      properties: {',
          "        color: '#333',",
          "        fontSize: '16px',",
          "        padding: '10px',",
          '      },',
          '    });',
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          "      props: { className: 'my-component' },",
          "      children: ['{{message}}'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '组件生命周期'),
      heading(3, '挂载阶段'),
      list([
        [inlineCode('beforeMount()'), ': 组件挂载到 DOM 前调用'],
        [inlineCode('onMounted()'), ': 组件挂载到 DOM 后调用'],
      ]),
      heading(3, '更新阶段'),
      list([
        [inlineCode('beforeUpdate()'), ': 组件状态更新前调用'],
        [inlineCode('onUpdated()'), ': 组件状态更新后调用'],
      ]),
      heading(3, '卸载阶段'),
      list([
        [inlineCode('beforeUnmount()'), ': 组件从 DOM 卸载前调用'],
        [inlineCode('onUnmounted()'), ': 组件从 DOM 卸载后调用'],
      ]),
      heading(3, '生命周期示例'),
      codeBlock(
        'ts',
        [
          'class LifecycleComponent extends Component<object, { count: number }> {',
          '  protected initState() {',
          '    return { count: 0 };',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected beforeMount() {',
          "    console.log('Component will mount');",
          '  }',
          '',
          '  protected onMounted() {',
          "    console.log('Component mounted');",
          '  }',
          '',
          '  protected beforeUpdate() {',
          "    console.log('Component will update');",
          '  }',
          '',
          '  protected onUpdated() {',
          "    console.log('Component updated');",
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'button',",
          "      children: ['Count: {{count}}'],",
          '      listeners: {',
          '        click: () => this.state.count++,',
          '      },',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '组件属性'),
      heading(3, '定义属性接口'),
      codeBlock(
        'ts',
        [
          'interface ButtonProps {',
          '  text: string;',
          '  disabled?: boolean;',
          "  size?: 'small' | 'medium' | 'large';",
          '}',
          '',
          'class Button extends Component<ButtonProps, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected render(): VNode {',
          "    const { text, disabled = false, size = 'medium' } = this.props;",
          '    return {',
          "      tag: 'button',",
          '      props: {',
          '        className: `btn btn-${size}` ,',
          '        disabled,',
          '      },',
          '      children: [text],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(3, '使用组件属性'),
      codeBlock(
        'ts',
        [
          'class ParentComponent extends Component<object, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          '      children: [',
          '        {',
          '          component: Button,',
          "          props: { text: 'Click Me', size: 'large' },",
          '        },',
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '组件事件'),
      heading(3, '发射事件'),
      codeBlock(
        'ts',
        [
          'class CounterComponent extends Component<object, { count: number }> {',
          '  protected initState() {',
          '    return { count: 0 };',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected handleIncrement() {',
          '    this.state.count++;',
          "    this.emit('increment', this.state.count);",
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'button',",
          '      listeners: { click: () => this.handleIncrement() },',
          "      children: ['+'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(3, '监听事件'),
      codeBlock(
        'ts',
        [
          'class ParentCounter extends Component<object, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected handleCounterChange(value: number) {',
          "    console.log('Counter changed:', value);",
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          '      children: [',
          '        {',
          '          component: CounterComponent,',
          '          listeners: {',
          '            increment: (value: number) => this.handleCounterChange(value),',
          '          },',
          '        },',
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '组件嵌套'),
      codeBlock(
        'ts',
        [
          'class App extends Component<object, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          "      props: { className: 'app' },",
          '      children: [',
          "        { tag: 'header', children: [{ component: NavigationComponent }] },",
          "        { tag: 'main', children: [{ component: HomeComponent }] },",
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '组件状态管理'),
      heading(3, '状态初始化'),
      codeBlock(
        'ts',
        [
          'protected initState() {',
          '  return {',
          '    count: 0,',
          "    user: { name: 'John', age: 30 },",
          "    items: ['Item 1', 'Item 2', 'Item 3'],",
          '  };',
          '}',
        ].join('\n')
      ),
      heading(3, '状态更新'),
      codeBlock(
        'ts',
        [
          'this.state.count = 1;',
          "this.state.user.name = 'Jane';",
          "this.state.items.push('Item 4');",
        ].join('\n')
      ),
      heading(2, '组件样式管理'),
      paragraph('每个组件实例都持有自己的 styleManager。'),
      heading(3, '添加样式'),
      codeBlock(
        'ts',
        [
          'protected initStyles() {',
          "  this.styleManager.addStyle('.button', {",
          "    selector: '.button',",
          '    properties: {',
          "      padding: '8px 16px',",
          "      backgroundColor: '#007bff',",
          "      color: '#fff',",
          '    },',
          '  });',
          '',
          "  this.styleManager.addStyle('.button:hover', {",
          "    selector: '.button:hover',",
          "    properties: { backgroundColor: '#0069d9' },",
          '  });',
          '}',
        ].join('\n')
      ),
      heading(3, '移除样式'),
      codeBlock(
        'ts',
        [
          "this.styleManager.removeStyle('.button');",
          'this.styleManager.clearStyles();',
        ].join('\n')
      ),
      heading(2, '组件上下文'),
      paragraph(
        '组件可以通过应用上下文读取全局配置，也可以通过 router getter 访问路由。'
      ),
      heading(3, '获取上下文'),
      codeBlock(
        'ts',
        [
          'const context = this.getContext();',
          'const router = this.router;',
          '',
          "router?.push('/about');",
          'console.log(context?.config);',
        ].join('\n')
      ),
      heading(2, '最佳实践'),
      heading(3, '组件设计原则'),
      list([
        ['单一职责：每个组件只负责一个功能'],
        ['可复用性：设计通用的、可复用的组件'],
        ['可维护性：保持组件代码简洁、清晰'],
        ['性能优化：避免不必要的渲染和计算'],
      ]),
      heading(3, '组件命名约定'),
      list([
        ['组件类名使用 PascalCase'],
        ['组件文件延续现有仓库的命名风格'],
        ['组件样式类名使用 kebab-case'],
      ]),
      heading(3, '性能优化技巧'),
      list([
        ['避免在 render 方法中创建不必要的新对象'],
        ['只将需要响应式更新的属性放在 state 中'],
        ['对复杂派生值使用 computed'],
        ['控制组件嵌套层级'],
      ]),
      heading(2, '总结'),
      paragraph(
        '通过类组件、生命周期、事件、插槽和局部样式管理，TSone 维持了清晰的面向对象组件模型。'
      ),
    ],
  },
  {
    path: '/guide/reactive-system/',
    title: '响应式系统',
    description:
      '掌握 reactive、effect、computed、readonly、ref 和 stop 的使用方式。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 4,
    body: [
      heading(1, '响应式系统'),
      paragraph(
        'TSone 的响应式系统允许您创建响应式状态，并在状态变化时自动更新 UI。'
      ),
      heading(2, '核心概念'),
      heading(3, '响应式对象'),
      paragraph(
        '响应式对象由 reactive 创建，会在属性访问和修改时自动追踪依赖。'
      ),
      heading(3, '副作用函数'),
      paragraph('副作用函数通过 effect 创建，会在依赖变化时重新执行。'),
      heading(3, '依赖追踪'),
      paragraph('框架会在 effect 运行期间记录访问过的响应式属性。'),
      heading(2, '核心 API'),
      heading(3, 'reactive'),
      codeBlock(
        'ts',
        [
          "import { reactive } from '@geektech/tsone';",
          '',
          'const state = reactive({',
          '  count: 0,',
          "  user: { name: 'John', age: 30 },",
          '});',
          '',
          'console.log(state.count);',
          'state.count = 1;',
        ].join('\n')
      ),
      heading(3, 'effect'),
      codeBlock(
        'ts',
        [
          "import { effect, reactive } from '@geektech/tsone';",
          '',
          'const state = reactive({ count: 0 });',
          '',
          'effect(() => {',
          '  console.log(`Count: ${state.count}`);',
          '});',
          '',
          'state.count = 1;',
          'state.count = 2;',
        ].join('\n')
      ),
      heading(3, 'computed'),
      codeBlock(
        'ts',
        [
          "import { computed, reactive } from '@geektech/tsone';",
          '',
          'const state = reactive({ count: 0 });',
          'const doubleCount = computed(() => state.count * 2);',
          '',
          'console.log(doubleCount.value);',
          'state.count = 1;',
          'console.log(doubleCount.value);',
        ].join('\n')
      ),
      heading(3, 'readonly'),
      codeBlock(
        'ts',
        [
          "import { reactive, readonly } from '@geektech/tsone';",
          '',
          'const original = reactive({ count: 0 });',
          'const readOnlyState = readonly(original);',
          '',
          'console.log(readOnlyState.count);',
          'original.count = 1;',
        ].join('\n')
      ),
      heading(3, 'ref'),
      codeBlock(
        'ts',
        [
          "import { effect, ref } from '@geektech/tsone';",
          '',
          'const count = ref(0);',
          '',
          'effect(() => {',
          '  console.log(`Count: ${count.value}`);',
          '});',
          '',
          'count.value += 1;',
        ].join('\n')
      ),
      heading(2, '响应式原理'),
      paragraph(
        'TSone 基于 JavaScript Proxy 拦截 get/set 来完成依赖收集和派发更新。'
      ),
      heading(3, '依赖追踪过程'),
      list([
        ['执行 effect，并将其标记为当前活动副作用'],
        ['在 effect 内部读取 reactive 或 ref 的值'],
        ['记录依赖关系'],
        ['当值变化时重新调度对应 effect'],
      ]),
      heading(2, '高级用法'),
      heading(3, '嵌套响应式对象'),
      codeBlock(
        'ts',
        [
          'const state = reactive({',
          "  user: { name: 'John', address: { city: 'New York' } },",
          '});',
          '',
          'effect(() => {',
          '  console.log(`${state.user.name} lives in ${state.user.address.city}`);',
          '});',
          '',
          "state.user.address.city = 'Los Angeles';",
        ].join('\n')
      ),
      heading(3, '数组响应式'),
      codeBlock(
        'ts',
        [
          "const state = reactive({ items: ['Item 1', 'Item 2'] });",
          '',
          'effect(() => {',
          "  console.log(state.items.join(', '));",
          '});',
          '',
          "state.items.push('Item 3');",
          "state.items[0] = 'Updated Item 1';",
        ].join('\n')
      ),
      heading(3, '条件依赖'),
      codeBlock(
        'ts',
        [
          "const state = reactive({ showCount: true, count: 0, message: 'Hello' });",
          '',
          'effect(() => {',
          '  if (state.showCount) {',
          '    console.log(`Count: ${state.count}`);',
          '  } else {',
          '    console.log(state.message);',
          '  }',
          '});',
        ].join('\n')
      ),
      heading(3, '清除副作用'),
      codeBlock(
        'ts',
        [
          "import { effect, reactive, stop } from '@geektech/tsone';",
          '',
          'const state = reactive({ count: 0 });',
          'const runner = effect(() => {',
          '  console.log(`Count: ${state.count}`);',
          '});',
          '',
          'stop(runner);',
        ].join('\n')
      ),
      heading(2, '最佳实践'),
      heading(3, '状态设计'),
      list([
        ['只把需要驱动 UI 的数据放进响应式对象'],
        ['根据业务模块组织状态，避免无意义的深层嵌套'],
        ['对复杂派生值优先使用 computed'],
      ]),
      heading(3, '性能优化'),
      list([
        ['为昂贵计算使用 computed 缓存'],
        ['避免在 effect 中执行重计算或副作用链式写入'],
        ['对不应该被写入的数据使用 readonly'],
      ]),
      heading(3, '常见陷阱'),
      list([
        ['不要直接替换整个 reactive 对象'],
        ['不要在 effect 内部无条件修改依赖状态'],
        ['嵌套对象会自动响应化，无需手动再次 reactive'],
      ]),
      heading(2, '与组件系统集成'),
      codeBlock(
        'ts',
        [
          'class CounterComponent extends Component<object, { count: number }> {',
          '  protected initState() {',
          '    return { count: 0 };',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'button',",
          "      children: ['Count: {{count}}'],",
          '      listeners: { click: () => this.state.count++ },',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '总结'),
      paragraph(
        '通过 reactive、effect、computed、readonly、ref 和 stop，TSone 为组件状态和独立数据模型提供了统一的响应式基础。'
      ),
    ],
  },
  {
    path: '/guide/router-system/',
    title: '路由系统',
    description:
      '使用 createRouter、RouterView 和 RouterLink 构建多页面前端体验。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 5,
    body: [
      heading(1, '路由系统'),
      paragraph('TSone 内置了路由系统，用于通过不同 URL 路径显示不同内容。'),
      heading(2, '核心概念'),
      heading(3, '路由实例'),
      paragraph('路由实例通过 createRouter 创建，负责管理路由配置和导航。'),
      heading(3, '路由配置'),
      paragraph('路由配置是一组 RouteRecord，定义路径与组件之间的映射关系。'),
      heading(3, '路由导航'),
      paragraph('您既可以编程式导航，也可以通过 RouterLink 进行声明式导航。'),
      heading(2, '基本使用'),
      heading(3, '安装路由'),
      codeBlock(
        'ts',
        "import { createRouter, RouterLink, RouterView } from '@geektech/tsone/router';"
      ),
      heading(3, '创建路由实例'),
      codeBlock(
        'ts',
        [
          "import { createApp } from '@geektech/tsone';",
          "import { createRouter, RouterView } from '@geektech/tsone/router';",
          '',
          'const router = createRouter({',
          '  routes: [',
          "    { path: '/', name: 'home', component: HomeComponent, meta: { title: '首页' } },",
          "    { path: '/about', name: 'about', component: AboutComponent, meta: { title: '关于我们' } },",
          "    { path: '/user/:id', name: 'user', component: UserComponent, meta: { title: '用户详情' } },",
          '  ],',
          "  mode: 'history',",
          "  base: '/',",
          '});',
          '',
          'const app = createApp({',
          '  root: class Layout extends Component<object, object> {',
          '    protected initState() {',
          '      return {};',
          '    }',
          '',
          '    protected initStyles(): void {}',
          '',
          '    protected render(): VNode {',
          '      return {',
          "        tag: 'main',",
          '        children: [{ component: RouterView }],',
          '      };',
          '    }',
          '  },',
          "  rootElement: '#app',",
          '});',
          '',
          'app.use(router);',
          'app.mount();',
        ].join('\n')
      ),
      heading(2, '路由配置选项'),
      heading(3, '路由规则'),
      list([
        [inlineCode('path'), ': URL 路径模式'],
        [inlineCode('name'), ': 路由名称'],
        [inlineCode('component'), ': 对应组件'],
        [inlineCode('meta'), ': 元数据'],
      ]),
      heading(3, '路径模式'),
      list([
        [inlineCode('/about'), ': 静态路径'],
        [inlineCode('/user/:id'), ': 动态路径参数'],
        [inlineCode('*'), ': 通配符兜底'],
      ]),
      heading(2, '路由导航'),
      heading(3, '编程式导航'),
      codeBlock(
        'ts',
        [
          "router.push('/about');",
          "router.replace('/login');",
          'router.back();',
          'router.forward();',
          'router.go(-1);',
        ].join('\n')
      ),
      heading(3, '声明式导航'),
      codeBlock(
        'ts',
        [
          '{',
          '  component: RouterLink,',
          '  props: {',
          "    to: '/user/42',",
          "    activeClass: 'is-active',",
          "    children: ['用户详情'],",
          '  },',
          '}',
        ].join('\n')
      ),
      heading(2, '路由参数'),
      heading(3, '获取路由参数'),
      codeBlock(
        'ts',
        [
          'class UserComponent extends Component<object, { userId: string }> {',
          '  protected initState() {',
          "    return { userId: '' };",
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected onMounted() {',
          '    const route = this.router?.getCurrentRoute();',
          "    this.state.userId = String(route?.params.id ?? '');",
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'h1',",
          "      children: ['用户详情 {{userId}}'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(3, '路由参数变化监听'),
      codeBlock(
        'ts',
        [
          'const stopListening = router.onRouteChange((to) => {',
          "  console.log('route changed to', to.path);",
          '});',
          '',
          'stopListening();',
        ].join('\n')
      ),
      heading(2, '路由元数据'),
      codeBlock(
        'ts',
        [
          'const router = createRouter({',
          '  routes: [',
          "    { path: '/', component: HomeComponent, meta: { title: '首页' } },",
          "    { path: '/dashboard', component: DashboardComponent, meta: { title: '仪表盘' } },",
          '  ],',
          '});',
        ].join('\n')
      ),
      heading(2, '路由模式'),
      heading(3, 'History 模式'),
      codeBlock(
        'ts',
        [
          'const router = createRouter({',
          "  mode: 'history',",
          '  routes: [...],',
          '});',
        ].join('\n')
      ),
      paragraph(
        'History 模式使用 HTML5 History API，需要服务器回退到应用入口。'
      ),
      heading(3, 'Hash 模式'),
      codeBlock(
        'ts',
        [
          'const router = createRouter({',
          "  mode: 'hash',",
          '  routes: [...],',
          '});',
        ].join('\n')
      ),
      paragraph('Hash 模式不需要服务器改写 URL，适合静态托管场景。'),
      heading(2, '嵌套路由'),
      paragraph('父组件中可以使用 RouterView 显示子路由内容。'),
      codeBlock(
        'ts',
        [
          'class DashboardComponent extends Component<object, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles(): void {}',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          '      children: [',
          "        { tag: 'h1', children: ['仪表盘'] },",
          '        { component: RouterView },',
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '路由 API'),
      heading(3, '路由实例方法'),
      list([
        [inlineCode('push(location)'), ': 导航到指定位置'],
        [inlineCode('replace(location)'), ': 替换当前历史记录'],
        [inlineCode('back() / forward() / go(n)'), ': 调用浏览器历史记录能力'],
        [inlineCode('onRouteChange(callback)'), ': 监听路由变化'],
        [inlineCode('getCurrentRoute()'), ': 读取当前路由信息'],
        [inlineCode('createHref(path)'), ': 生成 href'],
      ]),
      heading(3, '路由对象属性'),
      list([
        [inlineCode('currentRoute'), ': 当前路由信息'],
        [inlineCode('routes'), ': 路由配置'],
        [inlineCode('mode'), ': 路由模式'],
        [inlineCode('base'), ': 基础路径'],
      ]),
      heading(2, '最佳实践'),
      heading(3, '路由组织'),
      list([
        ['集中管理路由配置'],
        ['为关键页面使用命名路由'],
        ['合理使用动态参数和 meta'],
      ]),
      heading(3, '性能优化'),
      list([
        ['保持路由组件边界清晰'],
        ['避免在 onRouteChange 中执行昂贵操作'],
        ['必要时拆分页面级组件'],
      ]),
      heading(3, '常见问题'),
      list([
        ['History 模式刷新 404：需要服务器回退规则'],
        ['路由参数变化不更新：监听路由变化并刷新数据'],
        ['嵌套路由不显示：确认父组件中渲染了 RouterView'],
      ]),
      heading(2, '总结'),
      paragraph(
        'TSone 路由系统通过 createRouter、RouterView 和 RouterLink 提供了清晰、轻量的导航能力。'
      ),
    ],
  },
  {
    path: '/guide/style-management/',
    title: '样式管理',
    description: '了解 StyleManager、组件内样式注入、动态样式和全局样式实践。',
    section: guideSection,
    sectionOrder: guideSectionOrder,
    order: 6,
    body: [
      heading(1, '样式管理'),
      paragraph(
        'TSone 提供了内置的样式管理系统，通过 StyleManager 类管理组件样式。'
      ),
      heading(2, '核心概念'),
      heading(3, 'StyleManager'),
      paragraph('每个组件实例都有 styleManager，可用于添加、修改和删除样式。'),
      heading(3, '样式对象'),
      list([
        [inlineCode('selector'), ': CSS 选择器'],
        [inlineCode('properties'), ': CSS 属性和值的映射'],
      ]),
      heading(2, '基本使用'),
      heading(3, '在组件中使用'),
      codeBlock(
        'ts',
        [
          "import { Component, VNode } from '@geektech/tsone';",
          '',
          'class ButtonComponent extends Component<object, object> {',
          '  protected initState() {',
          '    return {};',
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.button', {",
          "      selector: '.button',",
          '      properties: {',
          "        padding: '8px 16px',",
          "        backgroundColor: '#007bff',",
          "        color: '#fff',",
          "        borderRadius: '4px',",
          '      },',
          '    });',
          '',
          "    this.styleManager.addStyle('.button:hover', {",
          "      selector: '.button:hover',",
          "      properties: { backgroundColor: '#0069d9' },",
          '    });',
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'button',",
          "      props: { className: 'button' },",
          "      children: ['Click Me'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '样式管理 API'),
      heading(3, '添加样式'),
      codeBlock(
        'ts',
        [
          "this.styleManager.addStyle('.container', {",
          "  selector: '.container',",
          '  properties: {',
          "    width: '100%',",
          "    maxWidth: '1200px',",
          "    margin: '0 auto',",
          "    padding: '0 15px',",
          '  },',
          '});',
        ].join('\n')
      ),
      heading(3, '移除样式'),
      codeBlock('ts', "this.styleManager.removeStyle('.container');"),
      heading(3, '清除所有样式'),
      codeBlock('ts', 'this.styleManager.clearStyles();'),
      heading(3, '获取样式'),
      codeBlock(
        'ts',
        [
          "const buttonStyle = this.styleManager.getStyle('.button');",
          'console.log(buttonStyle);',
        ].join('\n')
      ),
      heading(2, '高级用法'),
      heading(3, '样式优先级'),
      list([
        ['更具体的选择器拥有更高优先级'],
        ['相同特异性下，后添加的规则会覆盖先添加的规则'],
      ]),
      heading(3, '响应式样式'),
      codeBlock(
        'ts',
        [
          "this.styleManager.addStyle('@media (max-width: 768px)', {",
          "  selector: '@media (max-width: 768px)',",
          '  properties: {',
          "    '.container': { padding: '10px' },",
          '  },',
          '});',
        ].join('\n')
      ),
      heading(3, '动态样式'),
      codeBlock(
        'ts',
        [
          'class DynamicStyleComponent extends Component<object, { isActive: boolean }> {',
          '  protected initState() {',
          '    return { isActive: false };',
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.box.active', {",
          "      selector: '.box.active',",
          "      properties: { backgroundColor: '#007bff' },",
          '    });',
          '  }',
          '',
          '  protected render(): VNode {',
          '    return {',
          "      tag: 'div',",
          '      props: {',
          "        className: `box ${this.state.isActive ? 'active' : ''}`,",
          '      },',
          '      listeners: {',
          '        click: () => {',
          '          this.state.isActive = !this.state.isActive;',
          '        },',
          '      },',
          "      children: ['Click to toggle'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(3, '全局样式'),
      codeBlock(
        'ts',
        [
          "import { createApp } from '@geektech/tsone';",
          '',
          'const app = createApp({',
          "  rootElement: '#app',",
          '});',
          '',
          "app.styleManager.addStyle('body', {",
          "  selector: 'body',",
          '  properties: {',
          '    fontFamily: \'-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif\',',
          "    fontSize: '16px',",
          "    lineHeight: '1.5',",
          '  },',
          '});',
        ].join('\n')
      ),
      heading(2, '样式管理原理'),
      heading(3, '样式注入'),
      list([
        ['创建 style 元素'],
        ['将样式规则转换为 CSS 字符串'],
        ['把 CSS 写入 style 元素'],
        ['将 style 元素注入到文档头部'],
      ]),
      heading(3, '样式更新'),
      list([
        ['更新内部样式存储'],
        ['重新生成 CSS 字符串'],
        ['刷新 style 元素内容'],
      ]),
      heading(2, '最佳实践'),
      heading(3, '样式组织'),
      list([
        ['每个组件优先管理自己的样式'],
        ['使用语义化类名'],
        ['把相关规则组织在一起'],
      ]),
      heading(3, '性能优化'),
      list([
        ['尽量在 initStyles() 中一次性添加样式'],
        ['减少运行时频繁添加和删除样式'],
        ['避免过于复杂的选择器'],
      ]),
      heading(3, '常见问题'),
      list([
        ['样式不生效：检查选择器和覆盖关系'],
        ['样式冲突：提高选择器特异性或增加命名空间'],
        ['动态样式性能：高频变化场景可考虑 CSS 变量'],
      ]),
      heading(2, '总结'),
      paragraph(
        'StyleManager 提供了轻量、可组合的组件样式管理方式，既适合局部样式，也能承载应用级全局样式。'
      ),
    ],
  },
];
