import { guidePages } from '../zh/guide';
import type { DocPage } from '../types';

const translations = new Map<string, string>([
  ['快速开始', 'Getting Started'],
  ['安装 TSone，创建第一个类组件应用，并使用 Bun 启动示例。', 'Install TSone, create your first class-component application, and start an example with Bun.'],
  ['本指南将帮助您快速上手 TSone 框架。', 'This guide helps you get started quickly with TSone.'],
  ['安装', 'Installation'],
  ['首先，您需要安装 TSone 包。项目默认使用 Bun：', 'First, install the TSone package. Projects use Bun by default:'],
  ['创建第一个应用', 'Create Your First Application'],
  ['1. 创建一个简单的组件', '1. Create a Simple Component'],
  ['2. 创建应用实例并挂载', '2. Create and Mount the Application'],
  ['不需要为默认挂载点传入 rootElement。createApp 默认使用 #app，应用创建后直接调用 app.mount()；如果页面中暂时没有对应元素，本次挂载会安全跳过。', 'You do not need to pass rootElement for the default mount point. createApp uses #app by default, so call app.mount() after creating the application; mounting safely does nothing when the element is not present.'],
  ['3. HTML 结构', '3. HTML Structure'],
  ['运行应用', 'Run the Application'],
  ['根目录的 bun run dev 会启动 playground/official-site 官网首页演练；也可以运行 bun run dev:admin 查看后台管理页演练。', 'bun run dev at the repository root starts the playground/official-site home-page demo. You can also run bun run dev:admin to view the admin dashboard demo.'],
  ['下一步', 'Next Steps'],
  ['了解 ', 'Learn about '],
  ['学习 ', 'Learn '],
  ['探索 ', 'Explore '],
  ['掌握 ', 'Master '],
  ['核心概念', 'Core Concepts'],
  ['组件系统', 'Component System'],
  ['响应式系统', 'Reactive System'],
  ['路由系统', 'Routing'],
  ['样式管理', 'Style Management'],
  ['理解应用实例、类组件、响应式系统、路由和样式管理之间的关系。', 'Understand how application instances, class components, reactivity, routing, and style management work together.'],
  ['本文档介绍 TSone 框架的核心概念，帮助您更好地理解框架的设计理念和工作原理。', 'This document introduces the core concepts of TSone to help you understand its design and how it works.'],
  ['1. 应用实例', '1. Application Instance'],
  ['应用实例是 TSone 应用的入口点，通过 ', 'An application instance is the entry point for a TSone application. Create one with '],
  [' 创建。', '.'],
  ['2. 组件', '2. Components'],
  ['所有组件都继承 ', 'All components extend '],
  ['，通过 ', ' and use '],
  [' 描述 UI。', ' to describe the UI.'],
  ['组件生命周期', 'Component Lifecycle'],
  ['组件挂载前调用', 'called before the component mounts'],
  ['组件挂载后调用', 'called after the component mounts'],
  ['组件更新前调用', 'called before the component updates'],
  ['组件更新后调用', 'called after the component updates'],
  ['组件卸载前调用', 'called before the component unmounts'],
  ['组件卸载后调用', 'called after the component unmounts'],
  ['组件渲染', 'Component Rendering'],
  ['组件通过 ', 'A component returns virtual nodes from '],
  [' 返回虚拟节点，渲染器会根据 VNode 类型选择文本、元素、组件或插槽策略。', '; the renderer selects a text, element, component, or slot strategy based on the VNode type.'],
  ['3. 响应式系统', '3. Reactivity System'],
  ['TSone 的响应式系统基于 Proxy 实现，常用 API 包括 ', 'TSone reactivity is implemented with Proxy. Common APIs include '],
  ['、', ', '],
  [' 和 ', ', and '],
  ['。', '.'],
  ['核心 API', 'Core APIs'],
  ['创建响应式对象', 'creates a reactive object'],
  ['创建副作用函数', 'creates an effect function'],
  ['创建计算属性', 'creates a computed value'],
  ['创建只读响应式对象', 'creates a readonly reactive object'],
  ['创建包装单值的响应式引用', 'creates a reactive reference that wraps one value'],
  ['4. 虚拟 DOM', '4. Virtual DOM'],
  ['虚拟 DOM 是对真实 DOM 的轻量级抽象。', 'The virtual DOM is a lightweight abstraction of the real DOM.'],
  ['虚拟 DOM 结构', 'Virtual DOM Structure'],
  ['5. 路由系统', '5. Routing'],
  [' 创建路由实例，并使用 ', ' creates a router instance. Use '],
  [' 与 ', ' and '],
  [' 参与渲染和导航。', ' for rendering and navigation.'],
  ['路由配置', 'Route Configuration'],
  ['6. 样式管理', '6. Style Management'],
  ['TSone 提供内置 ', 'TSone provides a built-in '],
  ['，每个组件实例都可以通过 ', '. Each component instance can manage styles through '],
  [' 管理样式。', '.'],
  ['样式定义', 'Style Definition'],
  ['7. 插件系统', '7. Plugin System'],
  ['插件通过 app.use() 安装，可向应用上下文和组件扩展能力。', 'Install plugins with app.use() to extend application context and components.'],
  ['插件示例', 'Plugin Example'],
  ['8. 事件系统', '8. Event System'],
  ['组件可以通过 emit/on 进行事件通知，on 返回取消订阅函数。', 'Components can notify through emit/on, and on returns an unsubscribe function.'],
  ['事件示例', 'Event Example'],
  ['9. 条件、列表、依赖与表单', '9. Conditions, Lists, Dependencies, and Forms'],
  ['VNode 的 ', 'VNode '],
  [' 控制元素、组件和插槽的挂载；', ' controls mounting for elements, components, and slots; '],
  [' 为列表提供稳定 key。', ' provides stable keys for lists.'],
  ['应用或组件可通过 ', 'Applications or components can provide dependencies with '],
  [' 提供依赖，子组件用 ', '. Child components use '],
  [' 获取最近的值。', ' to retrieve the closest value.'],
  ['原生表单节点通过 ', 'Native form nodes bind state through '],
  [' 绑定状态，校验由独立的 ', '. Validation is handled by a separate '],
  [' 控制器完成。', ' controller.'],
  ['总结', 'Summary'],
  ['以上概念共同组成 TSone 的应用模型；继续阅读 ', 'Together, these concepts form TSone\'s application model. Continue with '],
  [' 与 ', ' and '],
  [' 可以看到更具体的代码模式。', ' for more concrete code patterns.'],
  ['学习基于 Component<Props, State> 的类组件、生命周期、事件和插槽。', 'Learn class components based on Component<Props, State>, lifecycle hooks, events, and slots.'],
  ['TSone 的组件系统允许您将 UI 拆分为独立、可复用的类组件。', 'TSone\'s component system lets you split UI into independent, reusable class components.'],
  ['组件定义', 'Component Definition'],
  ['组件通过继承 ', 'Define a component by extending '],
  [' 定义，并实现 ', ' and implementing '],
  ['、', ', '],
  [' 和 ', ', and '],
  ['。', '.'],
  ['基本组件结构', 'Basic Component Structure'],
  ['组件生命周期', 'Component Lifecycle'],
  ['挂载阶段', 'Mounting Phase'],
  ['组件挂载到 DOM 前调用', 'called before the component is mounted in the DOM'],
  ['组件挂载到 DOM 后调用', 'called after the component is mounted in the DOM'],
  ['更新阶段', 'Update Phase'],
  ['组件状态更新前调用', 'called before component state updates'],
  ['组件状态更新后调用', 'called after component state updates'],
  ['卸载阶段', 'Unmounting Phase'],
  ['组件从 DOM 卸载前调用', 'called before the component is removed from the DOM'],
  ['组件从 DOM 卸载后调用', 'called after the component is removed from the DOM'],
  ['生命周期示例', 'Lifecycle Example'],
  ['组件属性', 'Component Props'],
  ['定义属性接口', 'Define a Props Interface'],
  ['使用组件属性', 'Use Component Props'],
  ['组件事件', 'Component Events'],
  ['发射事件', 'Emit an Event'],
  ['监听事件', 'Listen for an Event'],
  ['组件嵌套', 'Component Nesting'],
  ['组件状态管理', 'Component State Management'],
  ['状态初始化', 'Initialize State'],
  ['状态更新', 'Update State'],
  ['组件样式管理', 'Component Style Management'],
  ['每个组件实例都持有自己的 styleManager。', 'Each component instance owns its own styleManager.'],
  ['添加样式', 'Add Styles'],
  ['移除样式', 'Remove Styles'],
  ['组件上下文', 'Component Context'],
  ['组件可以通过应用上下文读取全局配置，也可以通过 router getter 访问路由。', 'Components can read global configuration through application context and access the router through the router getter.'],
  ['获取上下文', 'Get Context'],
  ['最佳实践', 'Best Practices'],
  ['组件设计原则', 'Component Design Principles'],
  ['单一职责：每个组件只负责一个功能', 'Single responsibility: each component should handle one concern'],
  ['可复用性：设计通用的、可复用的组件', 'Reusability: design general-purpose, reusable components'],
  ['可维护性：保持组件代码简洁、清晰', 'Maintainability: keep component code concise and clear'],
  ['性能优化：避免不必要的渲染和计算', 'Performance: avoid unnecessary rendering and computation'],
  ['组件命名约定', 'Component Naming Conventions'],
  ['组件类名使用 PascalCase', 'Use PascalCase for component class names'],
  ['组件文件延续现有仓库的命名风格', 'Follow the repository\'s existing naming style for component files'],
  ['组件样式类名使用 kebab-case', 'Use kebab-case for component style class names'],
  ['性能优化技巧', 'Performance Tips'],
  ['避免在 render 方法中创建不必要的新对象', 'Avoid creating unnecessary objects in render'],
  ['只将需要响应式更新的属性放在 state 中', 'Keep only properties requiring reactive updates in state'],
  ['对复杂派生值使用 computed', 'Use computed for complex derived values'],
  ['控制组件嵌套层级', 'Keep component nesting shallow'],
  ['通过类组件、生命周期、事件、插槽和局部样式管理，TSone 维持了清晰的面向对象组件模型。', 'With class components, lifecycle hooks, events, slots, and local style management, TSone maintains a clear object-oriented component model.'],
  ['掌握 reactive、effect、computed、readonly、ref 和 stop 的使用方式。', 'Master reactive, effect, computed, readonly, ref, and stop.'],
  ['TSone 的响应式系统允许您创建响应式状态，并在状态变化时自动更新 UI。', 'TSone\'s reactivity system lets you create reactive state and automatically update the UI when it changes.'],
  ['响应式对象', 'Reactive Objects'],
  ['响应式对象由 reactive 创建，会在属性访问和修改时自动追踪依赖。', 'reactive creates reactive objects that automatically track dependencies when properties are read and changed.'],
  ['副作用函数', 'Effect Functions'],
  ['副作用函数通过 effect 创建，会在依赖变化时重新执行。', 'effect creates effect functions that run again when dependencies change.'],
  ['依赖追踪', 'Dependency Tracking'],
  ['框架会在 effect 运行期间记录访问过的响应式属性。', 'The framework records reactive properties accessed while an effect runs.'],
  ['响应式原理', 'How Reactivity Works'],
  ['TSone 基于 JavaScript Proxy 拦截 get/set 来完成依赖收集和派发更新。', 'TSone uses JavaScript Proxy to intercept get/set operations, collect dependencies, and dispatch updates.'],
  ['依赖追踪过程', 'Dependency Tracking Process'],
  ['执行 effect，并将其标记为当前活动副作用', 'Run effect and mark it as the active effect'],
  ['在 effect 内部读取 reactive 或 ref 的值', 'Read reactive or ref values inside effect'],
  ['记录依赖关系', 'Record the dependency relationship'],
  ['当值变化时重新调度对应 effect', 'Schedule the corresponding effect again when values change'],
  ['高级用法', 'Advanced Usage'],
  ['嵌套响应式对象', 'Nested Reactive Objects'],
  ['数组响应式', 'Reactive Arrays'],
  ['条件依赖', 'Conditional Dependencies'],
  ['清除副作用', 'Stop an Effect'],
  ['状态设计', 'State Design'],
  ['只把需要驱动 UI 的数据放进响应式对象', 'Put only data that drives the UI into reactive objects'],
  ['根据业务模块组织状态，避免无意义的深层嵌套', 'Organize state by business module and avoid meaningless deep nesting'],
  ['对复杂派生值优先使用 computed', 'Prefer computed for complex derived values'],
  ['性能优化', 'Performance Optimization'],
  ['为昂贵计算使用 computed 缓存', 'Use computed caching for expensive calculations'],
  ['避免在 effect 中执行重计算或副作用链式写入', 'Avoid expensive calculations or chained side-effect writes in effect'],
  ['对不应该被写入的数据使用 readonly', 'Use readonly for data that should not be written'],
  ['常见陷阱', 'Common Pitfalls'],
  ['不要直接替换整个 reactive 对象', 'Do not replace an entire reactive object directly'],
  ['不要在 effect 内部无条件修改依赖状态', 'Do not unconditionally modify dependency state inside effect'],
  ['嵌套对象会自动响应化，无需手动再次 reactive', 'Nested objects become reactive automatically; do not call reactive again manually'],
  ['与组件系统集成', 'Integration with Components'],
  ['通过 reactive、effect、computed、readonly、ref 和 stop，TSone 为组件状态和独立数据模型提供了统一的响应式基础。', 'With reactive, effect, computed, readonly, ref, and stop, TSone provides a unified reactive foundation for component state and standalone data models.'],
  ['使用 createRouter、RouterView 和 RouterLink 构建多页面前端体验。', 'Build multi-page frontend experiences with createRouter, RouterView, and RouterLink.'],
  ['TSone 内置了路由系统，用于通过不同 URL 路径显示不同内容。', 'TSone includes a routing system for showing different content at different URL paths.'],
  ['路由实例', 'Router Instance'],
  ['路由实例通过 createRouter 创建，负责管理路由配置和导航。', 'A router instance is created with createRouter and manages route configuration and navigation.'],
  ['路由配置是一组 RouteRecord，定义路径与组件之间的映射关系。', 'Route configuration is a set of RouteRecord values that map paths to components.'],
  ['路由导航', 'Route Navigation'],
  ['您既可以编程式导航，也可以通过 RouterLink 进行声明式导航。', 'You can navigate programmatically or declaratively with RouterLink.'],
  ['基本使用', 'Basic Usage'],
  ['安装路由', 'Import the Router'],
  ['创建路由实例', 'Create a Router Instance'],
  ['路由配置选项', 'Route Configuration Options'],
  ['路由规则', 'Route Rules'],
  ['URL 路径模式', 'URL path pattern'],
  ['路由名称', 'route name'],
  ['对应组件', 'associated component'],
  ['元数据', 'metadata'],
  ['路径模式', 'Path Patterns'],
  ['静态路径', 'static path'],
  ['动态路径参数', 'dynamic path parameter'],
  ['通配符兜底', 'wildcard fallback'],
  ['编程式导航', 'Programmatic Navigation'],
  ['声明式导航', 'Declarative Navigation'],
  ['路由参数', 'Route Parameters'],
  ['获取路由参数', 'Read Route Parameters'],
  ['路由参数变化监听', 'Listen for Route Parameter Changes'],
  ['路由元数据', 'Route Metadata'],
  ['路由模式', 'Routing Modes'],
  ['History 模式', 'History Mode'],
  ['History 模式使用 HTML5 History API，需要服务器回退到应用入口。', 'History mode uses the HTML5 History API and requires the server to fall back to the application entry point.'],
  ['Hash 模式', 'Hash Mode'],
  ['Hash 模式不需要服务器改写 URL，适合静态托管场景。', 'Hash mode does not require server URL rewrites and is suitable for static hosting.'],
  ['嵌套路由', 'Nested Routes'],
  ['父组件中可以使用 RouterView 显示子路由内容。', 'Parent components can use RouterView to display child-route content.'],
  ['路由 API', 'Router API'],
  ['路由实例方法', 'Router Instance Methods'],
  ['导航到指定位置', 'navigate to a location'],
  ['替换当前历史记录', 'replace the current history entry'],
  ['调用浏览器历史记录能力', 'use browser history'],
  ['监听路由变化', 'listen for route changes'],
  ['读取当前路由信息', 'read current route information'],
  ['生成 href', 'generate an href'],
  ['路由对象属性', 'Router Object Properties'],
  ['当前路由信息', 'current route information'],
  ['路由配置', 'route configuration'],
  ['路由模式', 'routing mode'],
  ['基础路径', 'base path'],
  ['路由组织', 'Route Organization'],
  ['集中管理路由配置', 'Manage route configuration centrally'],
  ['为关键页面使用命名路由', 'Use named routes for key pages'],
  ['合理使用动态参数和 meta', 'Use dynamic parameters and meta appropriately'],
  ['保持路由组件边界清晰', 'Keep route component boundaries clear'],
  ['避免在 onRouteChange 中执行昂贵操作', 'Avoid expensive work in onRouteChange'],
  ['必要时拆分页面级组件', 'Split page-level components when needed'],
  ['History 模式刷新 404：需要服务器回退规则', 'History-mode refresh returns 404: configure a server fallback rule'],
  ['路由参数变化不更新：监听路由变化并刷新数据', 'Route parameter changes do not update: listen for route changes and refresh data'],
  ['嵌套路由不显示：确认父组件中渲染了 RouterView', 'Nested routes do not display: confirm the parent renders RouterView'],
  ['TSone 路由系统通过 createRouter、RouterView 和 RouterLink 提供了清晰、轻量的导航能力。', 'TSone routing provides clear, lightweight navigation through createRouter, RouterView, and RouterLink.'],
  ['了解 StyleManager、组件内样式注入、动态样式和全局样式实践。', 'Learn about StyleManager, component style injection, dynamic styles, and global style practices.'],
  ['TSone 提供了内置的样式管理系统，通过 StyleManager 类管理组件样式。', 'TSone provides a built-in style management system that uses StyleManager to manage component styles.'],
  ['StyleManager', 'StyleManager'],
  ['每个组件实例都有 styleManager，可用于添加、修改和删除样式。', 'Every component instance has a styleManager for adding, changing, and removing styles.'],
  ['样式对象', 'Style Objects'],
  ['CSS 选择器', 'CSS selector'],
  ['CSS 属性和值的映射', 'mapping of CSS properties to values'],
  ['在组件中使用', 'Use in a Component'],
  ['样式管理 API', 'Style Management API'],
  ['清除所有样式', 'Clear All Styles'],
  ['获取样式', 'Get Styles'],
  ['样式优先级', 'Style Priority'],
  ['更具体的选择器拥有更高优先级', 'More specific selectors have higher priority'],
  ['相同特异性下，后添加的规则会覆盖先添加的规则', 'With equal specificity, rules added later override earlier rules'],
  ['响应式样式', 'Responsive Styles'],
  ['动态样式', 'Dynamic Styles'],
  ['全局样式', 'Global Styles'],
  ['样式管理原理', 'How Style Management Works'],
  ['样式注入', 'Style Injection'],
  ['创建 style 元素', 'Create a style element'],
  ['将样式规则转换为 CSS 字符串', 'Convert style rules to a CSS string'],
  ['把 CSS 写入 style 元素', 'Write CSS into the style element'],
  ['将 style 元素注入到文档头部', 'Inject the style element into the document head'],
  ['样式更新', 'Style Updates'],
  ['更新内部样式存储', 'Update internal style storage'],
  ['重新生成 CSS 字符串', 'Regenerate the CSS string'],
  ['刷新 style 元素内容', 'Refresh the style element content'],
  ['样式组织', 'Style Organization'],
  ['每个组件优先管理自己的样式', 'Each component should primarily manage its own styles'],
  ['使用语义化类名', 'Use semantic class names'],
  ['把相关规则组织在一起', 'Keep related rules together'],
  ['尽量在 initStyles() 中一次性添加样式', 'Add styles together in initStyles() whenever possible'],
  ['减少运行时频繁添加和删除样式', 'Reduce frequent runtime style additions and removals'],
  ['避免过于复杂的选择器', 'Avoid overly complex selectors'],
  ['样式不生效：检查选择器和覆盖关系', 'Styles do not apply: check selectors and overrides'],
  ['样式冲突：提高选择器特异性或增加命名空间', 'Style conflicts: increase selector specificity or add a namespace'],
  ['动态样式性能：高频变化场景可考虑 CSS 变量', 'Dynamic style performance: consider CSS variables for high-frequency changes'],
  ['StyleManager 提供了轻量、可组合的组件样式管理方式，既适合局部样式，也能承载应用级全局样式。', 'StyleManager provides lightweight, composable component style management for both local styles and application-wide global styles.'],
  ['计数', 'Count'],
  ['增加计数', 'Increment Count'],
  ['TSone 示例', 'TSone Example'],
  ['首页', 'Home'],
  ['关于我们', 'About Us'],
  ['用户详情', 'User Details'],
  ['仪表盘', 'Dashboard'],
  ['请输入姓名', 'Please enter a name'],
  ['通过', 'through'],
  ['常见问题', 'Common Issues'],
]);

const translationsByLength = [...translations.entries()].sort(
  ([left], [right]) => right.length - left.length
);

function translateValue(value: unknown): unknown {
  if (typeof value === 'string') {
    return translationsByLength.reduce(
      (translated, [source, target]) => translated.split(source).join(target),
      value
    );
  }

  if (Array.isArray(value)) {
    return value.map(translateValue);
  }

  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, translateValue(item)])
    );
  }

  return value;
}

export const enGuidePages: DocPage[] = translateValue(guidePages) as DocPage[];
