import { codeBlock, heading, list, paragraph, type DocPage } from './types';

export const examplePages: DocPage[] = [
  {
    path: '/examples/basic/',
    title: '基础示例',
    description: '基础示例覆盖 Hello World、计数器、表单处理和列表渲染。',
    section: 'Examples',
    sectionOrder: 3,
    order: 1,
    body: [
      heading(1, '基础示例'),
      paragraph('本文档展示 TSone 的基础使用示例。'),
      heading(2, 'Hello World'),
      codeBlock(
        'ts',
        [
          "import { createApp, Component } from '@geektech/tsone';",
          '',
          'class App extends Component<object, { message: string }> {',
          '  protected initState() {',
          "    return { message: 'Hello, TSone!' };",
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.app', {",
          "      selector: '.app',",
          "      properties: { textAlign: 'center', padding: '20px', fontSize: '24px' },",
          '    });',
          '  }',
          '',
          '  protected render() {',
          '    return {',
          "      tag: 'div',",
          "      props: { className: 'app' },",
          "      children: ['{{message}}'],",
          '    };',
          '  }',
          '}',
          '',
          "createApp({ root: App, rootElement: '#app' }).mount();",
        ].join('\n')
      ),
      heading(2, '计数器'),
      codeBlock(
        'ts',
        [
          'class Counter extends Component<object, { count: number }> {',
          '  protected initState() {',
          '    return { count: 0 };',
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.counter', {",
          "      selector: '.counter',",
          "      properties: { textAlign: 'center', padding: '20px' },",
          '    });',
          '  }',
          '',
          '  protected increment() {',
          '    this.state.count++;',
          '  }',
          '',
          '  protected decrement() {',
          '    this.state.count--;',
          '  }',
          '',
          '  protected render() {',
          '    return {',
          "      tag: 'div',",
          "      props: { className: 'counter' },",
          '      children: [',
          "        { tag: 'h2', children: ['Count: {{count}}'] },",
          "        { tag: 'button', listeners: { click: () => this.decrement() }, children: ['-'] },",
          "        { tag: 'button', listeners: { click: () => this.increment() }, children: ['+'] },",
          '      ],',
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '表单处理'),
      codeBlock(
        'ts',
        [
          'class FormExample extends Component<object, { name: string; email: string; message: string }> {',
          '  protected initState() {',
          "    return { name: '', email: '', message: '' };",
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.form', {",
          "      selector: '.form',",
          "      properties: { maxWidth: '500px', margin: '0 auto', padding: '20px' },",
          '    });',
          '  }',
          '',
          '  protected handleSubmit(event: Event) {',
          '    event.preventDefault();',
          "    console.log('Form submitted:', this.state);",
          '  }',
          '',
          '  protected render() {',
          '    return {',
          "      tag: 'form',",
          "      props: { className: 'form' },",
          '      listeners: { submit: (event: Event) => this.handleSubmit(event) },',
          "      children: ['...表单字段省略...'],",
          '    };',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '列表渲染'),
      codeBlock(
        'ts',
        [
          'class ListExample extends Component<object, { items: string[]; newItem: string }> {',
          '  protected initState() {',
          "    return { items: ['Item 1', 'Item 2', 'Item 3'], newItem: '' };",
          '  }',
          '',
          '  protected initStyles() {',
          "    this.styleManager.addStyle('.list-app', {",
          "      selector: '.list-app',",
          "      properties: { maxWidth: '500px', margin: '0 auto', padding: '20px' },",
          '    });',
          '  }',
          '',
          '  protected addItem() {',
          '    if (this.state.newItem.trim()) {',
          '      this.state.items.push(this.state.newItem);',
          "      this.state.newItem = '';",
          '    }',
          '  }',
          '',
          '  protected removeItem(index: number) {',
          '    this.state.items.splice(index, 1);',
          '  }',
          '}',
        ].join('\n')
      ),
      heading(2, '结论'),
      list([
        ['组件创建和挂载'],
        ['状态管理'],
        ['事件处理'],
        ['样式管理'],
        ['表单处理'],
        ['列表渲染'],
      ]),
    ],
  },
];
