import { StyleManager } from '../../style/StyleManager';
import { ComponentInstance } from '../renderer';
import type { VNode } from '../vnode';
export type ComponentProps = object;
export type ComponentState = object;
export type ComponentEventListener = (...args: unknown[]) => void;
export type InjectionKey<T> = (string | symbol) & {
    readonly __injectionType?: T;
};
export interface InjectionResult<T> {
    found: boolean;
    value: T | undefined;
}
export type ComponentConstructor<TProps extends ComponentProps = ComponentProps, TState extends ComponentState = ComponentState> = new (props?: TProps) => Component<TProps, TState>;
export type AnyComponentConstructor = new (props?: never) => Component<ComponentProps, ComponentState>;
export declare abstract class Component<TProps extends ComponentProps = ComponentProps, TState extends ComponentState = ComponentState> implements ComponentInstance {
    protected props: TProps;
    private vnode;
    private el;
    private readonly renderer;
    private readonly templateEngine;
    private readonly childComponents;
    private readonly eventListeners;
    private readonly providers;
    private readonly updateEffect;
    private appContext;
    private parentComponent;
    private elementChangeListener;
    protected styleManager: StyleManager;
    state: TState;
    mounted: boolean;
    constructor(props?: TProps);
    protected abstract initState(): TState;
    protected abstract initStyles(): void;
    protected abstract render(): VNode;
    mount(container: HTMLElement): void;
    mountToNode(): Node;
    update(): void;
    unmount(): void;
    setProps(props: Partial<TProps>): void;
    setState(state: Partial<TState>): void;
    setAppContext(context: unknown): void;
    setParentComponent(parent: ComponentInstance | null): void;
    setElementChangeListener(listener: (previousElement: Node, nextElement: Node) => void): void;
    provide<T>(key: InjectionKey<T>, value: T): void;
    inject<T>(key: InjectionKey<T>): T | undefined;
    inject<T>(key: InjectionKey<T>, fallback: T): T;
    resolveInjection<T>(key: InjectionKey<T>): InjectionResult<T>;
    getElement(): Node | null;
    protected beforeMount(): void;
    protected onMounted(): void;
    protected beforeUpdate(): void;
    protected onUpdated(): void;
    protected beforeUnmount(): void;
    protected onUnmounted(): void;
    protected getContext(): unknown;
    protected get router(): unknown;
    protected emit(eventName: string, ...args: unknown[]): void;
    on(eventName: string, listener: ComponentEventListener): () => void;
    off(eventName: string, listener: ComponentEventListener): void;
    private createRenderContext;
    private collectSlots;
    private getSlotName;
    private normalizeSlotChild;
    private trackStateProperties;
    private getRouterFrom;
    private getRouterFromGlobalApp;
    private resolveAppInjection;
    private trackReactiveValue;
}
